// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package main

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name: "PlaySoundDesktopLogin",
			Fn:   v.PlaySoundDesktopLogin,
		},
		{
			Name:   "Play",
			Fn:     v.Play,
			InArgs: []string{"theme", "event", "device"},
		},
		{
			Name:   "SaveAudioState",
			Fn:     v.SaveAudioState,
			InArgs: []string{"activePlayback"},
		},
		{
			Name:   "EnableSoundDesktopLogin",
			Fn:     v.EnableSoundDesktopLogin,
			InArgs: []string{"enabled"},
		},
		{
			Name:   "SetSoundTheme",
			Fn:     v.SetSoundTheme,
			InArgs: []string{"theme"},
		},
	}
}
