// Code generated by "dbusutil-gen em -type Helper"; DO NOT EDIT.

package main

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Helper) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:   "SetLocale",
			Fn:     v.SetLocale,
			InArgs: []string{"locale"},
		},
		{
			Name:   "GenerateLocale",
			Fn:     v.GenerateLocale,
			InArgs: []string{"locale"},
		},
	}
}
