package main

var xsInfoMap = map[string]string{
        "Xft/Antialias":                 "1;0",
        "Gtk/RecentFilesMaxAge":         "4294967295;0",
        "Net/EnableInputFeedbackSounds": "0;0",
        "Gtk/FontName":                  "Cantarell 11;1",
        "Net/DoubleClickTime":           "400;0",
        "Gtk/ShellShowsAppMenu":         "0;0",
        "Xft/Hinting":                   "1;0",
        "Gtk/Modules":                   "canberra-gtk-module;1",
        "Gtk/IMStatusStyle":             "callback;1",
        "Gtk/CursorThemeName":           "Deepin;1",
        "Gtk/IMModule":                  "fcitx;1",
        "Gtk/CanChangeAccels":           "0;0",
        "Gtk/ToolbarStyle":              "both-horiz;1",
        "Xft/RGBA":                      "none;1",
        "Gtk/ColorPalette":              "black:white:gray50:red:purple:blue:light blue:green:yellow:orange:lavender:brown:goldenrod4:dodger blue:pink:light green:gray10:gray30:gray75:gray90;1",
        "Gtk/ShowUnicodeMenu":           "1;0",
        "Xft/HintStyle":                 "hintmedium;1",
        "Net/EnableEventSounds":         "1;0",
        "Gtk/MenuBarAccel":              "F10;1",
        "Gtk/ToolbarIconSize":           "large;1",
        "Gtk/ButtonImages":              "0;0",
        "Gtk/IMPreeditStyle":            "callback;1",
        "Gtk/TimeoutInitial":            "200;0",
        "Gtk/CursorBlinkTimeout":        "10;0",
        "Net/DndDragThreshold":          "8;0",
        "Gtk/ColorScheme":               ";1",
        "Gtk/CursorThemeSize":           "24;0",
        "Xft/DPI":                       "98304;0",
        "Gtk/MenuImages":                "1;0",
        "Gtk/KeyThemeName":              "Default;1",
        "Gtk/EnableAnimations":          "1;0",
        "Gtk/RecentFilesEnabled":        "1;0",
        "Net/SoundThemeName":            "LinuxDeepin;1",
        "Net/CursorBlinkTime":           "1200;0",
        "Gtk/ShowInputMethodMenu":       "1;0",
        "Net/ThemeName":                 "Deepin;1",
        "Gtk/TimeoutRepeat":             "20;0",
        "Net/IconThemeName":             "Deepin;1",
        "Net/FallbackIconTheme":         "gnome;1",
        "Net/CursorBlink":               "1;0",
        "Gtk/AutoMnemonics":             "0;0",
}
