// Code generated by "dbusutil-gen em -type Manager"; DO NOT EDIT.

package main

import (
	"pkg.deepin.io/lib/dbusutil"
)

func (v *Manager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "GetFestivalMonth",
			Fn:      v.GetFestivalMonth,
			InArgs:  []string{"year", "month"},
			OutArgs: []string{"jsonStr"},
		},
		{
			Name:    "GetFestivalsInRange",
			Fn:      v.GetFestivalsInRange,
			InArgs:  []string{"start", "end"},
			OutArgs: []string{"result"},
		},
		{
			Name:    "GetHuangLiDay",
			Fn:      v.GetHuangLiDay,
			InArgs:  []string{"year", "month", "day"},
			OutArgs: []string{"jsonStr"},
		},
		{
			Name:    "GetHuangLiMonth",
			Fn:      v.GetHuangLiMonth,
			InArgs:  []string{"year", "month", "fill"},
			OutArgs: []string{"jsonStr"},
		},
		{
			Name:    "GetLunarInfoBySolar",
			Fn:      v.GetLunarInfoBySolar,
			InArgs:  []string{"year", "month", "day"},
			OutArgs: []string{"lunarDay", "ok"},
		},
		{
			Name:    "GetLunarMonthCalendar",
			Fn:      v.GetLunarMonthCalendar,
			InArgs:  []string{"year", "month", "fill"},
			OutArgs: []string{"lunarMonth", "ok"},
		},
	}
}
