// Code generated by "dbusutil-gen em -type Device"; DO NOT EDIT.

package main

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Device) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "HasBluetoothDeviceBlocked",
			Fn:      v.HasBluetoothDeviceBlocked,
			OutArgs: []string{"has"},
		},
		{
			Name: "UnblockBluetoothDevices",
			Fn:   v.UnblockBluetoothDevices,
		},
	}
}
