/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api/themes/scanner/testdata/Themes/Gtk1/metacity-1/metacity-theme-3.xml -a ./dde-api/toolGenerate/qdbusxml2cpp/metacity-theme-3Adaptor -i ./dde-api/toolGenerate/qdbusxml2cpp/metacity-theme-3.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef METACITY-THEME-3ADAPTOR_H
#define METACITY-THEME-3ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api/toolGenerate/qdbusxml2cpp/metacity-theme-3.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

#endif
