/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api/themes/scanner/testdata/Themes/Gtk1/metacity-1/metacity-theme-3.xml -a ./dde-api/toolGenerate/qdbusxml2cpp/metacity-theme-3Adaptor -i ./dde-api/toolGenerate/qdbusxml2cpp/metacity-theme-3.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api/toolGenerate/qdbusxml2cpp/metacity-theme-3Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

